### PR TITLE
[search] optional rng, only shuffle when present (fixes #107)

### LINKED ISSUE #107: Search without rng should do linear scan

### PR DESCRIPTION
**Pull request by anurudhp**

### CODE REVIEW

**Comment by catch22** [comment]
Excellent, I was going to suggest this 👍👍👍 Could you also update the `find_shor` example in the docs accordingly?

**Comment by catch22** [comment]
If `rng=None` and linear scan is used, shouldn't the classical number of queries also be adjusted to what the linear scan actually does?

**Comment by anurudhp** [comment]
> If `rng=None` and linear scan is used, shouldn't the classical number of queries also be adjusted to what the linear scan actually does?

So you mean actual queries = expected queries in this case? Yeah I think that makes sense.

**Comment by catch22** [comment]
Yes indeed, expected = actual if there is no randomness because the linear scan algorithm is deterministic.

**Pull request merged**
